### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by chaoslife** [darnton/BabylonBlazorDemo#1]
Is there some roadmap about babylon factory or on Blazor WASM?

**Comment by darnton** [comment]
I did this a demo and I'm only adding things as I need them, so no roadmap.

There's another project at https://github.com/canhorn/EventHorizon.Blazor.Interop.Generator which might be worth a look if what you want to do isn't covered by my stuff.

**Comment by chaoslife** [comment]
well done!
